name: Create and upload chocolatey package to JFrog
on:
  workflow_dispatch:
    inputs:
      BUILD_PATH:
        description: "Build path"
        required: true
        default: "\\\\dev.us.corp\\de\\Dev\\DailyBuilds\\60046\\NET CD Structure\\UltiProWeb\\Sync Service.msi"
      BUILD_VERSION:
        description: "Build version"
        required: true
        default: "8.0.3"
jobs:
  build:
    runs-on: [garm, dev, us-east4, vm, windows, medium]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Choco package
        run: |
          if (-not (Get-Command choco -ErrorAction SilentlyContinue)) {
            Write-Output "Chocolatey is not installed. Installing Chocolatey..."
            Set-ExecutionPolicy Bypass -Scope Process -Force; 
            [System.Net.ServicePointManager]::SecurityProtocol = [System.Net.ServicePointManager]::SecurityProtocol -bor 3072; 
            iwr https://community.chocolatey.org/install.ps1 -UseBasicParsing | iex
          } else {
            Write-Output "Chocolatey is already installed."
          }

      - name: Setup JFrog Cli
        uses: jfrog/setup-jfrog-cli@v4
        env:
          JF_PROJECT: ${{ vars.JFROG_PROJECT_KEY }}
          JF_URL: ${{ vars.JFROG_ARTIFACTORY_URL }}
          JF_ACCESS_TOKEN: ${{ secrets.JFROG_TOKEN }}

      - name: Create checksum
        run: |
          $secureNetworkPassword = ConvertTo-SecureString "password" -AsPlainText -Force
          $networkCredential = New-Object System.Management.Automation.PSCredential ("username, $secureNetworkPassword)
          
          $folderPath = [System.IO.Path]::GetDirectoryName("${{ github.event.inputs.BUILD_PATH }}")
          $file = [System.IO.Path]::GetFileName("${{ github.event.inputs.BUILD_PATH }}")
          
          New-PSDrive -Name Z -PSProvider FileSystem -Root  $folderPath -Credential $networkCredential 
          $hash = Get-FileHash "Z:\$file" -Algorithm SHA256
          Remove-PSDrive -Name Z

          Write-Output "Checksum created."

      - name: Create package
        run: |
          $scriptPath = "${{ github.workspace }}\scripts\create-package.ps1"
          & $scriptPath -version "${{ github.event.inputs.BUILD_VERSION }}" -buildPath "${{ github.event.inputs.BUILD_PATH }}"
          Write-Host "Package processed successfully: $msiName"

      - name: Upload package
        run: |
          jf rt u ".\packs\${{ github.event.inputs.MSI_NAME }}.${{ github.event.inputs.VERSION }}.nupkg" ${{ vars.JFROG_PACKAGE_REPOSITORY }}

