name: Create and upload chocolatey package to JFrog
on:
  workflow_dispatch:
    inputs:
      MSI_NAME:
        description: 'MSI Name'
        required: true
      VERSION:
        description: 'Version'
        required: true
      MSI_PATH:
        description: 'MSI PATH'
        required: true
jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        
      - name: Setup Choco package
        run:  Set-ExecutionPolicy Bypass -Scope Process -Force; [System.Net.ServicePointManager]::SecurityProtocol = [System.Net.ServicePointManager]::SecurityProtocol -bor 3072; iwr https://community.chocolatey.org/install.ps1 -UseBasicParsing | iex

      - name: Install JFROG CLI
        uses: jfrog/setup-jfrog-cli@v4
        env:
          JF_URL: ${{ vars.JFROG_ARTIFACTORY_URL }}
          JF_ACCESS_TOKEN: ${{ secrets.JFROG_TOKEN }} 

      - name: Create package 
        run: |
         $scriptPath = "${{ github.workspace }}\scripts\create-package.ps1"
         & $scriptPath -version "${{ github.event.inputs.VERSION }}" -msiName "${{ github.event.inputs.MSI_NAME }}" -msiPath "${{ github.event.inputs.MSI_PATH }}"
 
      - name: Upload package
        run: |
          jf rt u ".\packs\${{ github.event.inputs.MSI_NAME }}.${{ github.event.inputs.VERSION }}.nupkg" ${{ vars.JFROG_REPOSITORY }}   
