name: Save Document to Firestore
on:
  workflow_dispatch:

jobs:
  save-document:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Google Cloud SDK
      uses: google-github-actions/setup-gcloud@v1
      with:
        version: 'latest'
        service_account_key: ${{ secrets.GCPKEY }}
        export_default_credentials: true
        
    - name: Google Auth
      id: auth
      uses: 'google-github-actions/auth@v2'
      with:
        credentials_json: '${{ secrets.GCPKEY }}'

    - name: Run PowerShell script
      shell: pwsh
      run: .\scripts\firestore_service.ps1
      env:
        GOOGLE_APPLICATION_CREDENTIALS: ${{ secrets.GCPKEY }}
        GITHUB_WORKSPACE: ${{ github.workspace }}
        GCP_PROJECT: ${{ secrets.GCPPROJECT }}
