name: Access Google Secret Manager

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Google Cloud SDK
      uses: google-github-actions/setup-gcloud@v1
      with:
        version: 'latest'
        service_account_key: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}

    - name: Authenticate with Google Cloud
      run: echo "${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}" | gcloud auth activate-service-account --key-file=-

    - name: Access Secret Manager
      id: access_secret
      run: |
        SECRET_NAME="your-secret-name"
        SECRET_VALUE=$(gcloud secrets versions access latest --secret=${SECRET_NAME})
        echo "SECRET_VALUE=${SECRET_VALUE}" >> $GITHUB_ENV

    - name: Use Secret
      run: echo "The secret value is: ${{ env.SECRET_VALUE }}"
