name: Install package for Customer
on:
  workflow_dispatch:
    inputs:
        CUSTOMER_NAME:
          description: 'Name of the Customer'
          required: true
          type: string
        
jobs:
  read-json:
    runs-on: self-hosted
    steps:
      - name: Set Path
        run: Set-Location -Path "${{ github.workspace }}"

      - name: Deploy package on VMs
        run: ./scripts/install-customer-packages.ps1 -customerName "${{ github.event.inputs.CUSTOMER_NAME }}"
        shell: pwsh

           
