name: Install package for Customer
on:
  workflow_dispatch:
    inputs:
        CUSTOMER_NAME:
          description: 'Name of the Customer'
          required: true
          type: string
        
jobs:
  read-json:
    runs-on: self-hosted
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set Path
        run: Set-Location -Path "${{ github.workspace }}"

      - name: Deploy package on VMs
        run: |
          & ./scripts/install-customer-packages.ps1 -customerName "${{ github.event.inputs.CUSTOMER_NAME }}"
        env:
          JFROG_REPOSITORY: ${{ vars.JFROG_REPOSITORY }}
          JFROG_ARTIFACTORY_URL: ${{ vars.JFROG_ARTIFACTORY_URL }}
          JFROG_USERID: ${{ vars.JFROG_USERID }}
          JFROG_TOKEN: ${{ secrets.JFROG_TOKEN }}
          ADMIN_USER: ${{ vars.ADMIN_USER }}
          ADMIN_PASSWORD: ${{ secrets.ADMIN_PASSWORD }}


           
