name: Install package for Customer
on:
  workflow_call:
    inputs:
        CUSTOMER_NAME:
          description: 'Name of the Customer'
          required: true
          type: string
        
jobs:
  read-json:
    runs-on: windows-latest
    steps:
      - name: Deploy package on VMs 
        run: ./scripts/deploy-package.ps1 -customerName "${{ github.event.inputs.CUSTOMER_NAME }}"
        shell: pwsh
           