name: Publish Chocolatey Package to JFrog

on:
  push:
    branches:
      - feature

jobs:
  publish:
    runs-on: ubuntu-latest
    

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    # This action sets up the JFrog CLI with the Artifactory URL and access token     
    - name: Install JFROG CLI
      uses: jfrog/setup-jfrog-cli@v4
      env:
        JF_URL: ${{ secrets.JFROG_ARTIFACTORY_URL }}
        JF_ACCESS_TOKEN: ${{ secrets.JFROG_TOKEN }} 
    - name: Install
      run: |
      