---
name: Build and Deploy MSI
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: windows-latest
    env:
      projectPath: "MSIDemo.22.0.0.43559.nupkg"
      gcpRepository: "chocopackages"
      packageName: "MSIDemo"
      packageVersion: "v1.0.0"
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup Choco package
        run: >
          Set-ExecutionPolicy Bypass -Scope Process

          Set-ExecutionPolicy Bypass -Scope Process -Force; [System.Net.ServicePointManager]::SecurityProtocol = [System.Net.ServicePointManager]::SecurityProtocol -bor 3072; iex ((New-Object System.Net.WebClient).DownloadString('https://community.chocolatey.org/install.ps1'))
      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          version: 'latest'
          service_account_key: ${{ secrets.GCPKEY }}
          export_default_credentials: true
      - name: Build and push artifact
        run: |
          # Example of uploading a file to the Google Artifact Registry
          # Replace with your specific artifact commands
          gcloud artifacts repositories create ${{env.gcpRepository}} --repository-format=generic --location=${{ secrets.GCPREGION }}
          gcloud artifacts generic upload --source=$artifactPath --project=${{ secrets.GCPPROJECT }} --location=${{ secrets.GCPREGION }} --repository=${{env.gcpRepository}} --package=${{env.packageName}} --version=${{env.packageVersion}}
  
 
