name: Download File from Network Share

on:
 workflow_dispatch:

jobs:
  download_file:
    runs-on: self-hosted  # Use the self-hosted runner

    steps:
    - name: Check out repository
      uses: actions/checkout@v3

    - name: Run PowerShell script to download file
      run: |
        Test-Connection -ComputerName "172.29.74.154" -Count 4
        Set-Item WSMan:\localhost\Client\TrustedHosts -Value "172.29.74.154" -Force
        powershell.exe -ExecutionPolicy Bypass -File "${{ github.workspace }}\archives\download-file.ps1"
