name: Install MSI on Customer VM

on:
  workflow_dispatch:
    inputs:
      customer_name:
        description: 'Customer name'
        required: true

jobs:
  install-msi:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up environment variables
        run: |
          echo "CUSTOMER_NAME=${{ github.event.inputs.customer_name }}" >> $GITHUB_ENV

      - name: Install Chocolatey
        run: |
          Set-ExecutionPolicy Bypass -Scope Process -Force; [System.Net.ServicePointManager]::SecurityProtocol = [System.Net.ServicePointManager]::SecurityProtocol -bor 3072; iex ((New-Object System.Net.WebClient).DownloadString('https://community.chocolatey.org/install.ps1'))

      - name: Run PowerShell script on remote machine
        uses: neilotoole/winrm-action@v1
        with:
          username: 'Sonata\m.abhisehek'
          password: 'Gv@123456'
          hostname: '172.29.74.154'
          command: |
            # Copy repository to remote host
            $repoPath = Join-Path -Path $env:GITHUB_WORKSPACE -ChildPath '.'
            Copy-Item -Path $repoPath -Destination C:\Temp\Repo -Recurse -Force

            # Set environment variable
            $customer_name = "${{ github.event.inputs.customer_name }}"

            # Read configuration file
            $configFile = "C:\Temp\Repo\test.json"
            $config = Get-Content -Raw -Path $configFile | ConvertFrom-Json

            # Get the MSI details for the specified customer
            $msiDetails = $config.$customer_name.msifile1[0]

            $name = $msiDetails.name
            $version = $msiDetails.version
            $msipath = Join-Path -Path "C:\Temp\Repo" -ChildPath $msiDetails.msipath
            $msiargs = $msiDetails.msiargs
            $nupkgpath = Join-Path -Path "C:\Temp\Repo" -ChildPath $msiDetails.nupkgpath

            # Install the nupkg file using Chocolatey
            choco install $name --source=$nupkgpath -y