name: Test
on:
  push:
    branches: [ Testing-branch]
  workflow_dispatch:

  
jobs:
  build:
    runs-on: [garm, dev, us-east4, vm, windows, medium]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        
      - name: Create package
        run: |
          Set-Item WSMan:\localhost\Client\TrustedHosts -Value "10.210.222.182" -Force

